vcpkg_download_distfile(
    ARCHIVE_PATH
    URLS "https://archive.apache.org/dist/arrow/arrow-${VERSION}/apache-arrow-${VERSION}.tar.gz"
    FILENAME apache-arrow-${VERSION}.tar.gz
    SHA512 89da6de7eb2513c797d6671e1addf40b8b156215b481cf2511fa69faa16547c52d8220727626eeda499e4384d276e03880cd920aaab41c3d15106743d51a90a6
)
vcpkg_extract_source_archive(
    SOURCE_PATH
    ARCHIVE ${ARCHIVE_PATH}
)

string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} "dynamic" ARROW_BUILD_SHARED)
string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} "static" ARROW_BUILD_STATIC)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}/cpp"
    OPTIONS
        -DARROW_BUILD_SHARED=${ARROW_BUILD_SHARED}
        -DARROW_BUILD_STATIC=${ARROW_BUILD_STATIC}
        -DARROW_BUILD_TESTS=OFF
        -DARROW_BUILD_BENCHMARKS=OFF
        -DARROW_BUILD_UTILITIES=OFF
        -DARROW_BUILD_INTEGRATION=OFF
        -DARROW_BUILD_EXAMPLES=OFF
        -DARROW_DEPENDENCY_SOURCE=BUNDLED
        -DARROW_PACKAGE_KIND=vcpkg
        -DARROW_IPC=ON
        -DARROW_COMPUTE=OFF
        -DARROW_CSV=OFF
        -DARROW_FILESYSTEM=OFF
        -DARROW_FLIGHT=OFF
        -DARROW_FLIGHT_SQL=OFF
        -DARROW_JSON=OFF
        -DARROW_PARQUET=OFF
        -DARROW_DATASET=OFF
        -DARROW_ACERO=OFF
        -DARROW_ORC=OFF
        -DARROW_JEMALLOC=OFF
        -DARROW_MIMALLOC=OFF
        -DARROW_S3=OFF
        -DARROW_GCS=OFF
        -DARROW_WITH_BROTLI=OFF
        -DARROW_WITH_BZ2=OFF
        -DARROW_WITH_LZ4=OFF
        -DARROW_WITH_SNAPPY=OFF
        -DARROW_WITH_ZLIB=OFF
        -DARROW_WITH_ZSTD=OFF
        -DARROW_WITH_RE2=OFF
        -DARROW_WITH_UTF8PROC=OFF
        -DARROW_SIMD_LEVEL=NONE
        -DARROW_RUNTIME_SIMD_LEVEL=NONE
        -DARROW_USE_GLOG=OFF
        -DARROW_ENABLE_THREADING=OFF
        -DBUILD_WARNING_LEVEL=PRODUCTION
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/Arrow)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/share/doc")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.txt")
