// AUTO-GENERATED by vgi-rpc/scripts/regenerate_launcher_parity_vectors.py
// DO NOT EDIT BY HAND.  Re-run the generator and commit the result.
//
// Each vector pins the byte-identical hash that
// vgi_rpc.launcher.compute_hash() produces for the given (argv, cwd,
// env) tuple.  The C++ ComputeLauncherHash() must match every entry.

#pragma once

#include <map>
#include <string>
#include <vector>

namespace duckdb::vgi::launcher::test {

struct ParityVector {
	const char *name;
	std::vector<std::string> argv;
	std::string cwd;
	std::map<std::string, std::string> env;
	const char *expected_hash;
};

inline const std::vector<ParityVector> &PythonParityVectors() {
	static const std::vector<ParityVector> kVectors = {
	    {
	        /*name=*/"empty_argv_empty_env",
	        /*argv=*/{},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"21499d847854c192",
	    },
	    {
	        /*name=*/"single_arg",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"13ddf92fa852a381",
	    },
	    {
	        /*name=*/"many_args",
	        /*argv=*/{"python", "-m", "foo", "--bar", "baz"},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"1d95f2117bce8c2d",
	    },
	    {
	        /*name=*/"argv_with_spaces",
	        /*argv=*/{"python", "/path with spaces/foo.py"},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"23664770f5414889",
	    },
	    {
	        /*name=*/"cwd_with_special_chars",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp/has spaces and \"quotes\"",
	        /*env=*/{},
	        /*expected_hash=*/"e87a8168b8665401",
	    },
	    {
	        /*name=*/"env_single",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp",
	        /*env=*/{{"VGI_RPC_FOO", "bar"}},
	        /*expected_hash=*/"70118f0ad5ea8bf3",
	    },
	    {
	        /*name=*/"env_multiple_sorted_by_python",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp",
	        /*env=*/{{"VGI_RPC_Z", "z"}, {"VGI_RPC_A", "a"}, {"VGI_RPC_M", "m"}},
	        /*expected_hash=*/"1000503273c593e4",
	    },
	    {
	        /*name=*/"env_with_quotes_and_backslash",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp",
	        /*env=*/{{"VGI_RPC_FOO", "a\"b\\c"}},
	        /*expected_hash=*/"f688dc41e1a4416d",
	    },
	    {
	        /*name=*/"env_value_with_spaces",
	        /*argv=*/{"python"},
	        /*cwd=*/"/tmp",
	        /*env=*/{{"VGI_RPC_FLAG", "value with spaces"}},
	        /*expected_hash=*/"48522da323b1a55d",
	    },
	    {
	        /*name=*/"argv_with_quotes_and_backslash",
	        /*argv=*/{"echo", "a\"b\\c"},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"cfcf140ab2f01b74",
	    },
	    {
	        /*name=*/"long_path",
	        /*argv=*/{"/usr/local/bin/very/long/path/to/the/worker/executable"},
	        /*cwd=*/"/tmp",
	        /*env=*/{},
	        /*expected_hash=*/"b6f2736f279afd0b",
	    },
	    {
	        /*name=*/"deep_cwd",
	        /*argv=*/{"python"},
	        /*cwd=*/"/var/folders/5z/abcdefghijklmnop/T/working/directory/deep/nesting",
	        /*env=*/{},
	        /*expected_hash=*/"a37badbdf41d0559",
	    },
	    {
	        /*name=*/"many_args_many_env",
	        /*argv=*/{"java", "-jar", "/opt/foo.jar", "-Dlog.level=INFO"},
	        /*cwd=*/"/var/folders/work",
	        /*env=*/{{"VGI_RPC_TOKEN", "secret"}, {"VGI_RPC_REGION", "us-west-2"}, {"VGI_RPC_BUCKET", "my-bucket"}},
	        /*expected_hash=*/"8abb635d646af180",
	    },
	};
	return kVectors;
}

} // namespace duckdb::vgi::launcher::test
