// © Copyright 2025-2026, Query.Farm LLC - https://query.farm
// SPDX-License-Identifier: Apache-2.0
//
// Layer-2 parity tests: assert that ComputeLauncherHash matches the bytes
// `vgi_rpc.launcher.compute_hash` would produce for each input.
//
// This is the cross-implementation contract gate.  If the Python launcher's
// hash format ever changes the vectors regenerate; if a refactor of the C++
// canonical-JSON builder breaks parity, every vector fails loudly here.
//
// Vectors are generated by:
//   uv run python ~/Development/vgi-rpc/scripts/regenerate_launcher_parity_vectors.py
//       > test/cpp/launcher_parity_vectors.hpp

#include "catch.hpp"

#include "vgi_launcher_internal.hpp"
#include "launcher_parity_vectors.hpp"

using duckdb::vgi::launcher::ComputeLauncherHash;
using duckdb::vgi::launcher::test::PythonParityVectors;

TEST_CASE("ComputeLauncherHash matches Python launcher byte-for-byte",
          "[launcher][parity]") {
	for (const auto &v : PythonParityVectors()) {
		// Catch2 doesn't have parametrized cases out of the box, so use
		// CAPTURE + section-style INFO to label which vector failed.
		INFO("vector: " << v.name);
		const auto actual = ComputeLauncherHash(v.argv, v.cwd, v.env);
		CHECK(actual == v.expected_hash);
	}
}
