#!/usr/bin/env python3
# © Copyright 2026, Query.Farm LLC - https://query.farm
# SPDX-License-Identifier: Apache-2.0
"""Generate the flat VGI settings registry, defaults and reference from one schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "src/vgi_settings.json"


def render():
    definitions = json.loads(SCHEMA.read_text())
    assert len({d["name"] for d in definitions}) == len(definitions)
    banner = "// Generated by scripts/generate_settings.py from src/vgi_settings.json. Do not edit.\n"
    header = banner + "#pragma once\n#include <cstdint>\n\nnamespace duckdb {\nnamespace vgi {\nnamespace defaults {\n"
    registry = banner
    rows = []
    for d in definitions:
        ident = d["name"].removeprefix("vgi_").upper()
        kind = d["type"]
        if kind == "BOOLEAN":
            cpp_type, default = "bool", str(d["default"]).lower()
        elif kind in ("BIGINT", "UBIGINT"):
            cpp_type = "int64_t" if kind == "BIGINT" else "uint64_t"
            default = str(d["default"]) + ("LL" if kind == "BIGINT" else "ULL")
            assert d["minimum"] <= d["default"] <= d["maximum"]
        elif kind == "VARCHAR":
            cpp_type, default = "const char *", json.dumps(d["default"])
        else:
            assert kind == "MAP(VARCHAR, BIGINT)"
            kind = "THRESHOLDS"
            # All object kinds currently share the same default; retain keys in the registry.
            assert len(set(d["default"].values())) == 1
            cpp_type, default = "int64_t", str(next(iter(d["default"].values()))) + "LL"
        if "wasm_default" in d:
            header += f"#ifdef __EMSCRIPTEN__\ninline constexpr {cpp_type} {ident} = {d['wasm_default']}LL;\n#else\n"
        header += f"inline constexpr {cpp_type}{'' if cpp_type.endswith('*') else ' '}{ident} = {default};\n"
        if "wasm_default" in d:
            header += "#endif\n"
        choices = ",".join(d.get("choices", d["default"].keys() if kind == "THRESHOLDS" else []))
        details = d["description"] + " Scope: " + d["scope"] + ". Takes effect: " + d["effect"]
        details += " Platform: " + d["platform"] + "."
        if "zero" in d:
            details += " Zero: " + d["zero"]
        if choices:
            details += (" Keys: " if kind == "THRESHOLDS" else " Choices: ") + choices + "."
        if "minimum" in d:
            details += f" Range: {d['minimum']}..{d['maximum']}."
        args = [ident, json.dumps(d["name"]), kind, str(d.get("minimum", 0)) + "ULL",
                str(d.get("maximum", 0)) + "ULL", json.dumps(choices),
                "true" if d["scope"] == "global" else "false", json.dumps(details)]
        registry += "VGI_SETTING(" + ", ".join(args) + ")\n"
        value = json.dumps(d["default"], ensure_ascii=False)
        if "wasm_default" in d:
            value += f" (WASM: {d['wasm_default']})"
        notes = d["description"]
        if choices:
            notes += " " + ("Keys" if kind == "THRESHOLDS" else "Choices") + ": " + choices.replace(",", ", ") + "."
        if "minimum" in d:
            notes += f" Range: {d['minimum']}–{d['maximum']}."
        if "zero" in d:
            notes += " **0:** " + d["zero"]
        rows.append(f"| `{d['name']}` | `{d['type']}` | `{value}` | {d['scope']} | {d['effect']} | {d['platform']} | {notes} |")
    header += "} // namespace defaults\n} // namespace vgi\n} // namespace duckdb\n"
    reference = ROOT / "docs/reference.md"
    original = reference.read_text()
    start = original.index("## Extension Settings")
    end = original.index("## ATTACH Options", start)
    section = """## Extension Settings

<!-- Generated by scripts/generate_settings.py from src/vgi_settings.json. -->

Settings remain flat SQL options. `SET name = value` and `RESET name` use the scope below.
Session settings also permit `SET GLOBAL` to change the database default; an explicit session
override takes precedence. Global settings reject `SET SESSION` and are shared by all connections
to the database instance. All VGI settings reject NULL. Enum values are case-insensitive and
stored in canonical lowercase. Unknown eager-load map keys are rejected.

Result-cache memory, counters and resource configuration belong to a database instance, not the
process. Separate databases cannot reconfigure one another's memory caches. Disk directories are
explicitly shared across databases/processes when configured to the same path; pruning and flush
operations can affect that shared disk content. Use separate directories for independent stores.
Changing the directory drops retained per-value arenas; active queries can finish with their old
arena/backend snapshots. Whole-result memory entries remain eligible for reuse.

`vgi_result_cache_max_bytes` is applied **separately** to the whole-result cache and per-value
memo arena accounting. Their combined accounted retention can approach **2 × max_bytes**, plus
tracked in-flight capture buffers up to `max_inflight_bytes` (unless zero/unbounded), active
readers, metadata and other query allocations. These are cache accounting limits, not an RSS cap.
The whole-result disk budget and per-value SQLite disk budget are also independent and enforced
through admission/cleanup rather than a filesystem quota. A zero whole-result disk budget does
not disable SQLite persistence; an empty `vgi_result_cache_dir` disables both disk tiers.

Worker pools remain process-wide and keyed by worker identity. Pool settings are defaults captured
at ATTACH and overridden by `pool_max` / `pool_timeout`; attaching the same worker path can update
its shared pool configuration. The maximum limits idle retention per bucket, not active execution
concurrency. Worker-package directories and credential stores can also be shared outside the database.

| Setting | Type | Default | Scope | Takes effect | Platform | Meaning and constraints |
|---------|------|---------|-------|--------------|----------|-------------------------|
""" + "\n".join(rows) + "\n\nCatalogs may register additional worker-defined settings at ATTACH; those are outside this registry.\n\n"
    return {ROOT / "src/include/vgi_settings_defaults.hpp": header,
            ROOT / "src/include/vgi_settings_registry.inc": registry,
            reference: original[:start] + section + original[end:]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, contents in render().items():
        if not path.exists() or path.read_text() != contents:
            if args.check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.write_text(contents)
    if stale:
        raise SystemExit("Regenerate settings with python3 scripts/generate_settings.py: " + ", ".join(stale))


if __name__ == "__main__":
    main()
