// Generated by scripts/generate_settings.py from src/vgi_settings.json. Do not edit.
#pragma once
#include <cstdint>

namespace duckdb {
namespace vgi {
namespace defaults {
inline constexpr const char *ALLOWED_TRANSPORTS = "all";
inline constexpr bool ASYNC_PREFETCH = false;
inline constexpr bool BATCH_LATERAL = true;
inline constexpr bool CANCEL_ENABLED = true;
inline constexpr bool CATALOG_CONTENTS = true;
inline constexpr int64_t EAGER_LOAD_THRESHOLD = 1000LL;
inline constexpr bool EXCHANGE_INPUT_DEDUP = true;
inline constexpr const char *GITHUB_CACHE_DIR = "";
#ifdef __EMSCRIPTEN__
inline constexpr int64_t HTTP_ACCEPTED_MAX_RESPONSE_BYTES = 67108864LL;
#else
inline constexpr int64_t HTTP_ACCEPTED_MAX_RESPONSE_BYTES = 268435456LL;
#endif
inline constexpr int64_t HTTP_TIMEOUT_SECONDS = 300LL;
inline constexpr int64_t IROH_CONNECT_TIMEOUT_SECONDS = 30LL;
inline constexpr int64_t IROH_IO_TIMEOUT_SECONDS = 300LL;
inline constexpr uint64_t JOIN_KEYS_MAX_BYTES = 67108864ULL;
inline constexpr bool MULTI_BRANCH_SCANS = true;
inline constexpr const char *OAUTH_CACHE = "auto";
inline constexpr bool OAUTH_ENABLED = true;
inline constexpr const char *OAUTH_FLOW = "auto";
inline constexpr const char *OAUTH_PROMPT = "none";
inline constexpr int64_t OAUTH_TIMEOUT_SECONDS = 120LL;
inline constexpr bool RESULT_CACHE = true;
inline constexpr uint64_t RESULT_CACHE_DEFAULT_TTL_SECONDS = 0ULL;
inline constexpr const char *RESULT_CACHE_DIR = "";
inline constexpr const char *RESULT_CACHE_DISK_COMPRESSION = "zstd";
inline constexpr uint64_t RESULT_CACHE_DISK_COMPRESSION_LEVEL = 1ULL;
inline constexpr uint64_t RESULT_CACHE_DISK_MAX_BYTES = 0ULL;
inline constexpr uint64_t RESULT_CACHE_DISK_REAP_INTERVAL_SECONDS = 60ULL;
inline constexpr uint64_t RESULT_CACHE_EXCHANGE_DISK_MAX_REFS = 100000ULL;
inline constexpr uint64_t RESULT_CACHE_MAX_BYTES = 268435456ULL;
inline constexpr uint64_t RESULT_CACHE_MAX_ENTRIES = 131072ULL;
inline constexpr uint64_t RESULT_CACHE_MAX_ENTRY_BYTES = 67108864ULL;
inline constexpr uint64_t RESULT_CACHE_MAX_INFLIGHT_BYTES = 268435456ULL;
inline constexpr bool RESULT_CACHE_PACK = true;
inline constexpr uint64_t RESULT_CACHE_PACK_COMPACTION_DEAD_PCT = 50ULL;
inline constexpr uint64_t RESULT_CACHE_PACK_MAX_ENTRY_BYTES = 262144ULL;
inline constexpr uint64_t RESULT_CACHE_PACK_TARGET_BYTES = 67108864ULL;
inline constexpr uint64_t RESULT_CACHE_PARTITION_MAX_ENUMERATED = 1024ULL;
inline constexpr bool RESULT_CACHE_PARTITION_SCOPE = true;
inline constexpr bool RESULT_CACHE_PER_VALUE = true;
inline constexpr uint64_t RESULT_CACHE_PER_VALUE_DISK_MAX_BYTES = 1073741824ULL;
inline constexpr uint64_t RESULT_CACHE_PER_VALUE_MAX_STORES_PER_CHUNK = 256ULL;
inline constexpr uint64_t RESULT_CACHE_REVALIDATE_MIN_BYTES = 262144ULL;
inline constexpr int64_t SECRET_DEFAULT_TTL_SECONDS = 300LL;
inline constexpr uint64_t SPLIT_PLAN_MAX_PAGES = 1024ULL;
inline constexpr bool SPLIT_SCANS = true;
inline constexpr uint64_t SPLIT_TOKEN_MIN_TTL_SECONDS = 30ULL;
inline constexpr bool STREAMING_WINDOW = true;
inline constexpr bool TABLE_BUFFERING = true;
inline constexpr uint64_t TARGET_SPLIT_BYTES = 0ULL;
inline constexpr bool TRUST_EMPTY_KINDS = true;
inline constexpr const char *VALIDATE_WORKER_BATCHES = "full";
inline constexpr const char *WORKER_CACHE_DIR = "";
inline constexpr uint64_t WORKER_CACHE_MAX_BYTES = 5368709120ULL;
inline constexpr uint64_t WORKER_CACHE_TTL_SECONDS = 2592000ULL;
inline constexpr uint64_t WORKER_PACKAGE_MAX_BYTES = 536870912ULL;
inline constexpr uint64_t WORKER_PACKAGE_MAX_EXTRACTED_BYTES = 1073741824ULL;
inline constexpr uint64_t WORKER_PACKAGE_MAX_FILES = 10000ULL;
inline constexpr int64_t WORKER_POOL_IDLE_LIMIT_SECONDS = 5LL;
inline constexpr int64_t WORKER_POOL_MAX = 256LL;
} // namespace defaults
} // namespace vgi
} // namespace duckdb
