// © Copyright 2025, 2026 Query Farm LLC - https://query.farm
#pragma once

#include <arrow/api.h>
#include <arrow/io/api.h>
#include <arrow/ipc/api.h>

#include <memory>
#include <functional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "duckdb/main/client_context.hpp"
// Relative: only ``src/include`` is on the include path, and these generated
// headers live beside it in ``src/generated``.
#include "../generated/vgi_protocol_names.hpp"
#include "../generated/vgi_protocol_version.hpp"
#include "../generated/vgi_secret_protocol_version.hpp"
#include "vgi_platform.hpp" // pid_t (real on POSIX, shim on Windows)

namespace duckdb {
namespace vgi {

// ============================================================================
// vgi_rpc Wire Protocol Constants
// ============================================================================

// Request metadata keys (written on request batches)
constexpr const char *RPC_METHOD_KEY = "vgi_rpc.method";
constexpr const char *RPC_REQUEST_VERSION_KEY = "vgi_rpc.request_version";
constexpr const char *RPC_REQUEST_VERSION_VALUE = "1";

// Application protocol surface version metadata key. The C++ extension
// emits ``VGI_PROTOCOL_VERSION`` (from ``vgi_protocol_version.hpp``,
// generated by ``vgi.codegen.cpp_protocol_version``) on every request
// batch. The vgi-rpc server enforces an exact major+minor match at the
// dispatch boundary; mismatches surface as IOException with directional
// "upgrade the client" / "upgrade the worker" guidance.
constexpr const char *RPC_PROTOCOL_VERSION_KEY = "vgi_rpc.protocol_version";

// Protocol routing key. A vgi-rpc server dispatches on the pair
// (protocol, method), not on the method alone: one server may co-host several
// protocols, method names are allowed to collide between them, and on the raw
// transports (subprocess, AF_UNIX, TCP, stdio, SAB, Iroh) this metadata key is
// the *only* carrier of which protocol a request addresses. Over HTTP the same
// value is also projected into the URL path segment, and the server rejects a
// request whose two carriers disagree.
//
// Required on every protocol-owned request. A request that omits it is
// unroutable — the server raises ProtocolNotSpecifiedError rather than guessing
// a default, precisely so a co-hosting server can never silently pick wrong.
constexpr const char *RPC_PROTOCOL_KEY = "vgi_rpc.protocol";

// ============================================================================
// Protocol Identity
// ============================================================================
//
// One application protocol this client addresses: the wire routing key it is
// reached by, and its independently-versioned method-and-schema surface. The
// two always travel together — a request stamped with one protocol's name and
// another's version is routed to a binding that then rejects it — so they are
// carried as a pair rather than as two loose strings.
//
// SOURCE OF TRUTH: vgi-python, and both halves are GENERATED — the names by
// ``vgi.codegen.cpp_protocol_name`` into ``vgi_protocol_names.hpp``, the versions
// by ``vgi.codegen.cpp_protocol_version`` / ``cpp_secret_protocol_version``.
// Regenerate with ``scripts/regen_generated.py``; vgi-python's
// ``tests/test_generated_cpp_*`` fail the build if either drifts.
//
// The names were hand-written on both sides until a rename proved why they
// should not be: a version bump that missed this tree was a red build, while a
// rename that missed it was a silent misroute that surfaced only as every
// request naming a protocol the server no longer hosted.
//
// Note the major version is part of the name. An incompatible major is a
// DIFFERENT protocol, so a stale client's request 404s instead of reaching a
// handler that then rejects it — an answer any proxy understands without an
// Arrow parser.
struct VgiProtocolId {
	// Value of RPC_PROTOCOL_KEY, and the HTTP path's protocol segment.
	std::string_view name;
	// Value of RPC_PROTOCOL_VERSION_KEY. Each protocol is versioned on its own:
	// the secret protocol's 1.x has nothing to do with the worker protocol's 2.x.
	std::string_view version;
};

// The worker/catalog protocol: bind/init, the catalog_* family, aggregates,
// table_buffering_*. Everything this extension sends except secret_lookup.
inline constexpr VgiProtocolId VGI_MAIN_PROTOCOL {::duckdb::vgi::generated::VGI_PROTOCOL_NAME,
                                                 ::duckdb::vgi::generated::VGI_PROTOCOL_VERSION};

// Orchard's standalone secret service: the single unary ``secret_lookup``.
// Versioned independently of the worker protocol, which is why the per-call
// version override existed before the routing key did.
inline constexpr VgiProtocolId VGI_SECRET_PROTOCOL {
    ::duckdb::vgi::generated::VGI_SECRET_PROTOCOL_NAME,
    ::duckdb::vgi::generated::VGI_SECRET_PROTOCOL_VERSION};

// Reserved, server-level methods (``__transport_options__``, ``__upload_url__``,
// ``__introspect_token__``) belong to no protocol: the server resolves them from
// a built-in table *before* routing, and over HTTP they are mounted flat at
// ``{prefix}/{method}`` rather than under a protocol segment. Stamping a routing
// key on one is not merely redundant — over HTTP the server compares the key
// against the resolved method's (empty) protocol name and rejects the mismatch.
inline bool IsReservedRpcMethod(const std::string &method_name) {
	return method_name.rfind("__", 0) == 0;
}

// Response/log/error metadata keys (read from response batches)
constexpr const char *RPC_LOG_LEVEL_KEY = "vgi_rpc.log_level";
constexpr const char *RPC_LOG_MESSAGE_KEY = "vgi_rpc.log_message";
constexpr const char *RPC_LOG_EXTRA_KEY = "vgi_rpc.log_extra";
constexpr const char *RPC_SERVER_ID_KEY = "vgi_rpc.server_id";
constexpr const char *RPC_REQUEST_ID_KEY = "vgi_rpc.request_id";

// HTTP streaming state token metadata key
constexpr const char *RPC_STREAM_STATE_KEY = "vgi_rpc.stream_state#b64";
// The stream's *call state* -- the half of a stream's state that is fixed for
// the life of the call (the init request, the resolved schemas). The worker
// mints it once on /init and never re-issues it; the client holds it and
// echoes it on every subsequent request so any worker can serve the turn
// without prior knowledge of the stream. Only RPC_STREAM_STATE_KEY (the
// cursor) comes back per turn.
constexpr const char *RPC_CALL_STATE_KEY = "vgi_rpc.call_state#b64";

// External location metadata key (pointer batch)
constexpr const char *RPC_LOCATION_KEY = "vgi_rpc.location";

// External location SHA-256 checksum metadata key (pointer batch)
constexpr const char *RPC_LOCATION_SHA256_KEY = "vgi_rpc.location.sha256";

// Transport capability negotiation (mirror vgi-rpc TransportOptions). The client
// calls TRANSPORT_OPTIONS_METHOD once per worker (before init) to discover which
// transport features the worker supports; capabilities ride as metadata under
// the vgi_rpc.transport.* namespace. shm is used only when both peers report it.
constexpr const char *TRANSPORT_OPTIONS_METHOD = "__transport_options__";
constexpr const char *TRANSPORT_CAP_SHM_KEY = "vgi_rpc.transport.shm";

// Shared-memory transport keys (mirror vgi_rpc/metadata.py).
// Set on the *request batch* to advertise a client-allocated segment to the
// worker; the worker may then write its response batches into the segment
// and emit "pointer batches" carrying offset/length per batch.
constexpr const char *SHM_SEGMENT_NAME_KEY = "vgi_rpc.shm_segment_name";
constexpr const char *SHM_SEGMENT_SIZE_KEY = "vgi_rpc.shm_segment_size";
// Set on response *pointer batches* (zero-row data batches with these
// metadata keys instead of vgi_rpc.log_level): the real batch lives at
// [shm_offset, shm_offset+shm_length) inside the segment.
constexpr const char *SHM_OFFSET_KEY = "vgi_rpc.shm_offset";
constexpr const char *SHM_LENGTH_KEY = "vgi_rpc.shm_length";
constexpr const char *SHM_SOURCE_KEY = "vgi_rpc.shm_source";

// ============================================================================
// Batch Classification
// ============================================================================
// Per wire protocol spec:
// - num_rows > 0 or no metadata → DATA
// - num_rows == 0 + vgi_rpc.log_level == "EXCEPTION" → ERROR (throw)
// - num_rows == 0 + vgi_rpc.log_level present → LOG (forward to logger)
// - Otherwise → DATA (void return / stream-finish)

enum class RpcBatchType {
	DATA,
	LOG,
	ERROR,
	EXTERNAL_LOCATION
};

// Classify a batch according to the vgi_rpc wire protocol.
// Does NOT throw or dispatch - just classifies.
RpcBatchType ClassifyBatch(const std::shared_ptr<arrow::RecordBatch> &batch,
                           const std::shared_ptr<arrow::KeyValueMetadata> &custom_metadata);

// ============================================================================
// Request Writing
// ============================================================================

// Write an RPC request with parameters to a file descriptor.
// Creates an IPC stream: schema (from params_batch) + 1-row batch with method metadata + EOS.
// The params_batch must have exactly 1 row with one field per method parameter.
void WriteRpcRequest(int fd, const std::string &method_name,
                     const std::shared_ptr<arrow::RecordBatch> &params_batch,
                     const std::shared_ptr<arrow::KeyValueMetadata> &extra_metadata = nullptr,
                     const VgiProtocolId &protocol = VGI_MAIN_PROTOCOL);

// Stream-based form used by transports that are not represented by an OS file
// descriptor (notably native Iroh QUIC streams). The framing is byte-for-byte
// identical to the fd form above.
void WriteRpcRequest(const std::shared_ptr<arrow::io::OutputStream> &sink,
                     const std::string &method_name,
                     const std::shared_ptr<arrow::RecordBatch> &params_batch,
                     const std::shared_ptr<arrow::KeyValueMetadata> &extra_metadata = nullptr,
                     const VgiProtocolId &protocol = VGI_MAIN_PROTOCOL);

// Write an RPC request with no parameters (zero-field schema, 1-row batch).
// Used for parameterless methods like catalog_catalogs.
void WriteEmptyRpcRequest(int fd, const std::string &method_name,
                          const VgiProtocolId &protocol = VGI_MAIN_PROTOCOL);

// ============================================================================
// Response Reading
// ============================================================================

// Result from reading a unary response
struct UnaryResponseResult {
	std::shared_ptr<arrow::RecordBatch> batch;           // The data batch (1-row with "result" column, or empty for void)
	std::shared_ptr<arrow::KeyValueMetadata> metadata;   // Custom metadata from the data batch
};

// Read a unary RPC response from a file descriptor.
// Opens an IPC stream reader, dispatches log batches, returns the first data batch.
// Throws IOException on EXCEPTION-level log batches.
// The response stream has schema with "result" column (or empty for void methods).
// worker_path/worker_pid are for error context.
// Blocks until the worker speaks or the query is cancelled — polls the
// context's `interrupted` flag every 250ms (Ctrl-C / query cancel) with no
// wall-clock deadline. A wedged worker is broken out of by cancellation; a
// legitimately-slow response (cold worker start, large catalog, slow upstream)
// is never killed by an arbitrary timeout. Cleanup of an interrupted-mid-RPC
// connection is the caller's responsibility (route through VgiCancelDispatcher
// so the worker unblocks).
UnaryResponseResult ReadUnaryResponse(int fd, ClientContext *context,
                                      const std::string &worker_path = "",
                                      pid_t worker_pid = -1,
                                      const std::string &invocation_id_hex = "",
                                      const std::string &attach_opaque_data_hex = "",
                                      const std::string &transaction_opaque_data_hex = "",
                                      const std::string &conn_id_hex = "");

// Stream-based response reader. Cancellation/deadline polling is provided by
// the InputStream implementation; the native Iroh stream uses short timed
// reads and cancels its QUIC stream when ClientContext is interrupted.
UnaryResponseResult ReadUnaryResponse(const std::shared_ptr<arrow::io::InputStream> &input,
                                      ClientContext *context,
                                      const std::string &worker_path = "",
                                      pid_t worker_pid = -1,
                                      const std::string &invocation_id_hex = "",
                                      const std::string &attach_opaque_data_hex = "",
                                      const std::string &transaction_opaque_data_hex = "",
                                      const std::string &conn_id_hex = "");

// Result from reading a stream header
struct StreamHeaderResult {
	std::shared_ptr<arrow::RecordBatch> header_batch;    // The header data batch (1-row)
	std::shared_ptr<arrow::KeyValueMetadata> metadata;   // Custom metadata from the header batch
};

// Read a stream header (phase 1.5) from a file descriptor.
// Opens an IPC stream reader on the header schema, dispatches log batches,
// returns the header data batch, and drains to EOS.
// Used for streaming RPC methods that declare a header type (e.g., init()).
StreamHeaderResult ReadStreamHeader(int fd, ClientContext *context,
                                    const std::string &worker_path = "",
                                    pid_t worker_pid = -1);

StreamHeaderResult ReadStreamHeader(const std::shared_ptr<arrow::io::InputStream> &input,
                                    ClientContext *context,
                                    const std::string &worker_path = "",
                                    pid_t worker_pid = -1);

// ============================================================================
// Buffer-based Serialization/Deserialization (for HTTP transport)
// ============================================================================

// Serialize an RPC request to bytes (same format as WriteRpcRequest but to buffer).
// Returns a complete Arrow IPC stream: schema + 1-row batch with method metadata + EOS.
// protocol: which application protocol this request addresses. Stamps both
// `vgi_rpc.protocol` (the routing key the server dispatches on) and
// `vgi_rpc.protocol_version`. Defaults to the worker/catalog protocol; the
// separately-versioned secret protocol passes VGI_SECRET_PROTOCOL.
// extra_metadata: additional (key,value) pairs folded into the request's
// custom_metadata alongside the method/version keys. Used by the HTTP transport to
// carry the result-cache conditional-revalidation validators (vgi.cache.if_none_match
// / if_modified_since) on the `/init` request, since over HTTP the worker's first
// producer turn runs inside /init and must see the validators before it produces.
std::vector<uint8_t> SerializeRpcRequest(
    const std::string &method_name, const std::shared_ptr<arrow::RecordBatch> &params_batch,
    const VgiProtocolId &protocol = VGI_MAIN_PROTOCOL,
    const std::vector<std::pair<std::string, std::string>> &extra_metadata = {});

// Serialize an RPC request with no parameters (zero-field schema, 1-row batch).
std::vector<uint8_t> SerializeEmptyRpcRequest(const std::string &method_name,
                                              const VgiProtocolId &protocol = VGI_MAIN_PROTOCOL);

// Parse a unary response from bytes (same logic as ReadUnaryResponse but from buffer).
// url is used for error context (replaces worker_path in fd-based version).
// The four *_hex parameters are forwarded to HandleBatchLogMessage so log
// batches embedded in unary RPC responses carry the same diagnostic fields
// that the streaming data path emits (conn=, attach=, etc.).
UnaryResponseResult ReadUnaryResponseFromBuffer(const uint8_t *data, size_t len,
                                                 ClientContext *context,
                                                 const std::string &url = "",
                                                 const std::string &invocation_id_hex = "",
                                                 const std::string &attach_opaque_data_hex = "",
                                                 const std::string &transaction_opaque_data_hex = "",
                                                 const std::string &conn_id_hex = "");

// Dispatch every Arrow IPC stream concatenated in an error response body,
// throwing on the first batch that carries error metadata.
//
// A STREAMING RPC answers with two concatenated IPC streams: a header stream
// (execution_id / max_workers / opaque_data) and a data stream under the
// function's own output schema. An IPC stream carries exactly one schema, so
// the two cannot be merged. That means an error raised AFTER the header was
// already written — a producer failing on its first next_batch — rides as
// metadata on a batch in the SECOND stream, where a single-stream read never
// looks. ReadUnaryResponseFromBuffer stops at the end of stream one, finds a
// perfectly valid header, and returns without throwing.
//
// This walks the whole body so those errors surface with the worker's message
// instead of a generic transport failure. Safe for a unary body too, which is
// simply one stream.
void DispatchErrorStreamsFromBuffer(const uint8_t *data, size_t len, ClientContext *context,
                                    const std::string &url = "");

// Move-in overload: adopts the response body string as the owning Arrow buffer
// (arrow::Buffer::FromString) instead of allocating + memcpying a copy of the
// whole payload. Prefer this whenever the caller owns the body and is done
// with it — e.g. HttpInvokeUnary handing over the decompressed HTTP response.
UnaryResponseResult ReadUnaryResponseFromBuffer(std::string &&body,
                                                 ClientContext *context,
                                                 const std::string &url = "",
                                                 const std::string &invocation_id_hex = "",
                                                 const std::string &attach_opaque_data_hex = "",
                                                 const std::string &transaction_opaque_data_hex = "",
                                                 const std::string &conn_id_hex = "");

// Result from reading a stream header from a buffer.
// For HTTP init responses: the response body contains header IPC stream + data IPC stream.
struct BufferStreamHeaderResult {
	StreamHeaderResult header;
	size_t data_offset;  // Byte offset where the data IPC stream begins
};

// Parse a stream header from a buffer.
// Reads the header IPC stream, dispatches log batches, returns header batch + data offset.
BufferStreamHeaderResult ReadStreamHeaderFromBuffer(const uint8_t *data, size_t len,
                                                     ClientContext *context,
                                                     const std::string &url = "");

// Owning-buffer overload: parses directly out of ``buffer`` with no copy.
// The returned header batch zero-copy references ``buffer`` — callers keep it
// alive implicitly via the batch's refcounted slices. Prefer this when the
// caller already owns the response body as an Arrow buffer (HTTP /init path:
// wrap the body once, parse the header here, then slice the data section at
// data_offset — the whole response is materialized exactly once).
BufferStreamHeaderResult ReadStreamHeaderFromBuffer(std::shared_ptr<arrow::Buffer> buffer,
                                                     ClientContext *context,
                                                     const std::string &url = "");

} // namespace vgi
} // namespace duckdb
